version: '3'

services:
  getir-case-study:
    build:
      context: .
      dockerfile: dockerfile
    image: getir-case-study${TAG:-latest}
    restart: unless-stopped
    environment:
      RECORD_DB_URL: "mongodb+srv://challengeUser:WUMglwNBaydH8Yvu@challenge-xzwqd.mongodb.net/getir-case-study?retryWrites=true"
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    ports:
      - "5071:5071"
    volumes:
      - .:/home/node/app/getir-case-study
      - node_modules:/home/node/app/getir-case-study/node_modules
    command: sh -c "npm start"

volumes:
  dbdata:
  node_modules: